// Bundles src/handler.ts to dist/handler.js for Lambda. Two-step:
//
//   1. **Snapshot starter-code into a generated TS module.** Walks
//      templates/static-site/starter-code/ at build time; emits
//      src/starter-code-snapshot/files.ts as a `Record<string, string>`
//      with each file's content inlined as a JSON string. The committed
//      version of files.ts is a stub (empty record) so typecheck/test
//      pass without running the build first; this script overwrites it.
//
//   2. **esbuild bundle.** Same shape as the other workflow Lambdas —
//      ESM, node22 target, @aws-sdk/* externalized.
//
// CI must run this build before terraform plan. The infra/modules/lambda
// module zips dist/ at plan time via archive_file.

import {
  readFileSync,
  writeFileSync,
  readdirSync,
  statSync,
  mkdirSync,
  rmSync,
} from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";
import * as esbuild from "esbuild";

const __dirname = dirname(fileURLToPath(import.meta.url));
const distDir = resolve(__dirname, "dist");
const starterCodeRoot = resolve(
  __dirname,
  "../../../templates/static-site/starter-code",
);
const snapshotFilePath = resolve(__dirname, "src/starter-code-snapshot/files.ts");

// Walk a directory tree, return [{path, content}] with paths relative
// to the root. Excludes the snapshot dir itself in case of accidental
// recursion (defensive).
const walk = (root, current = root, prefix = "") => {
  const entries = readdirSync(current);
  const result = [];
  for (const entry of entries) {
    const full = resolve(current, entry);
    const rel = prefix ? `${prefix}/${entry}` : entry;
    const stat = statSync(full);
    if (stat.isDirectory()) {
      result.push(...walk(root, full, rel));
    } else if (stat.isFile()) {
      result.push({ path: rel, content: readFileSync(full, "utf-8") });
    }
  }
  return result;
};

const files = walk(starterCodeRoot);
files.sort((a, b) => a.path.localeCompare(b.path));

const snapshotTs = [
  "// Auto-generated by build.mjs from templates/static-site/starter-code/.",
  "// Do not edit — changes will be overwritten on next build. The committed",
  "// version is a stub for typecheck (empty record); CI's build step",
  "// populates the real content before bundling. See build.mjs for the",
  "// snapshot mechanism.",
  "",
  "export const STARTER_CODE_FILES: Record<string, string> = {",
  ...files.map(
    (f) => `  ${JSON.stringify(f.path)}: ${JSON.stringify(f.content)},`,
  ),
  "};",
  "",
].join("\n");

writeFileSync(snapshotFilePath, snapshotTs);
console.log(`snapshot: ${files.length} files → ${snapshotFilePath}`);

rmSync(distDir, { recursive: true, force: true });
mkdirSync(distDir, { recursive: true });

await esbuild.build({
  entryPoints: [resolve(__dirname, "src/handler.ts")],
  outfile: resolve(distDir, "handler.js"),
  bundle: true,
  format: "esm",
  platform: "node",
  target: "node22",
  sourcemap: false,
  minify: false,
  external: ["@aws-sdk/*", "@smithy/*"],
  logLevel: "info",
});

writeFileSync(
  resolve(distDir, "package.json"),
  JSON.stringify({ type: "module" }, null, 2) + "\n",
);
