// Auto-generated by build.mjs from templates/static-site/starter-code/.
// Do not edit — changes will be overwritten on next build. This
// committed version is a stub for typecheck/test (empty record); CI's
// build step populates the real content before bundling. See build.mjs
// for the snapshot mechanism.
//
// Do NOT commit a populated version — git diffs would be noisy on every
// starter-code change. The stub + build-time populate keeps the
// committed file stable while letting the bundle ship real content.

export const STARTER_CODE_FILES: Record<string, string> = {};
